[package]
name = "visa-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
visa-rs = "0.4.0"
csv = "1.1"